### ISSUE TITLE
Implement Context#create_function

### ISSUE THREAD

**Issue by judofyr** [judofyr/duktape.rb#16]
```ruby
ctx.define_function "hello" do |a, b|
  a + b
end
ctx.eval_string("hello(1, 2)", __FILE__) # => 3.0
```

**Comment by judofyr** [comment]
Closing this until someone needs it.

**Comment by did** [comment]
hi @judofyr! First, thanks for your work! 
Actually, I'd need it (http://duktape.org/guide.html#gettingstarted.4). 
To be honest, I've got no experience about native extensions but I could figure out something with the help of my friend google.

**Comment by judofyr** [comment]
What's the use case? Do you only need to define global functions? Do you want to handle prototypes? What about "this"?

**Comment by judofyr** [comment]
Also: do you want to have Ruby objects available in JS?

**Comment by did** [comment]
@judofyr I want my users to write small JS scripts interacting with some parts of my ruby code in the safest way possible. A simple example:

````ruby
my_action = <<JS
if (create('Users', { name: params.name, email: params.email }))
   sendEmail('Welcome', params.email, 'Hello world');
JS
````

Both create and sendEmail are defined function like you described it at the top of the issue.

````ruby
ctx.define_function "sendEmail" do |title, to, body|
  # my ruby code to send an email
end
ctx.define_function "create" do |content_type, params|
  # my ruby code to persist a model of a content type
end
ctx.eval_string(my_action, __FILE__) 
````

Of course, something flexible like therubyracer gem offers would be awesome but the define_function implementation is just enough for a v0.

thanks!

**Comment by did** [comment]
I started the implementation. Right now I'm stuck because I can't figure out how to pass my block (yield) to the C function I pushed to the context as described in the Duktype API (duk_push_c_function). 
I imagine that I need to push it to the context and retrieve it in my pushed C function.

**Comment by did** [comment]
Alright, my implementation of the define_function validates this unit test:

````ruby
   def test_call_prop
      @ctx.define_function("square") { |x| x * x }
      @ctx.define_function("inc") { |x| x + 1 }
      @ctx.eval_string('function math(a) { return square(inc(a)) }')
      assert_equal 9, @ctx.call_prop('math', 2)
    end
````
I've to clean my C code of course but looks like I made it ;-) I'll push my commit to my branch tomorrow and perhaps send you a PR if you're interested in.
