### ISSUE TITLE
Figure out what we need for ExecJS

### ISSUE THREAD

**Issue by judofyr** [judofyr/duktape.rb#17]
/cc @josh

**Comment by josh** [comment]
Update on the CoffeeScript compatibility.

On Duktape 1.1.1 + a TBD CoffeeScript 1.9.2 should be working.

**Comment by judofyr** [comment]
Anything more we need for a release?

**Comment by josh** [comment]
:+1: Looking pretty good to me. Should be able to have an ExecJS release out soon supporting it.

**Comment by josh** [comment]
https://github.com/rails/execjs/pull/1 is green.
