### ISSUE TITLE
Release 1.1.2.0

### ISSUE THREAD

**Issue by josh** [judofyr/duktape.rb#19]
@judofyr any objections to cutting a 1.1.0.0 gem?

**Comment by judofyr** [comment]
Nothing else than it would be nice with a better README/documentation.

**Comment by josh** [comment]
Revised my request to 1.1.2 :wink:

**Comment by judofyr** [comment]
Again: I'd really like some documentation (aka. public API).

**Comment by josh** [comment]
I can try to help out there.

Are you thinking just putting it all in the readme or should we attempt the C-style rdoc inline comments to generate the API docs?

**Comment by judofyr** [comment]
Just a README is fine for me. Same is rdoc. Everything is awesome.

**Comment by josh** [comment]
Any other docs I can help with?

**Comment by judofyr** [comment]
Done:

* https://github.com/judofyr/duktape.rb/releases/tag/v1.1.2.0
* https://rubygems.org/gems/duktape/versions/1.1.2.0

**Comment by josh** [comment]
:tada:
