### ISSUE TITLE
Support Bundler git target

### ISSUE THREAD

**Issue by josh** [judofyr/duktape.rb#22]
It'd be nice to be able to test duktape.rb from a Bundle git target.

``` ruby
gem "duktape", github: "judofyr/duktape.rb"
```

I think it doesn't work because `ext/duktape/duktape.c` and `ext/duktape/duktape.h` aren't checked in

```
duktape at /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/bundler/gems/duktape.rb-fe2d192bdb5d did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
If you need to use this package without installing it from a gem repository, please contact judofyr@gmail.com and ask them to modify their .gemspec so it can work with `gem build`.
The validation message from Rubygems was:
  ["ext/duktape/duktape.c", "ext/duktape/duktape.h"] are not files
```

I think theres a few ways to work around this if we really don't want to check these files in. Instead of the rake file downloading the files, executing the `.gemspec` would probably need to.

Any objections to just checking in the source or should I look into this alternate approach? I'll get a PR going for either, but just wanted your feedback first.

/cc @judofyr

**Comment by judofyr** [comment]
Duktape is like ~1MB of source code. Bundling each version could lead to a huge Git repo. Checking it into source would be fine *if* you can show that Git compresses it properly.

Here's a nice test we should do:

* Create a new repo.
* Download the first version of Duktape (the big duktape.c/h-file) and store it.
* Commit.
* Download the next version. Commit. Repeat until we're done.
* Check the repo size.

**Comment by judofyr** [comment]
Here's the size in kilobytes after adding each version to Git.

```ruby
0.6.0: 492
0.7.0: 564
0.8.0: 636
0.9.0: 724
0.10.0: 832
0.11.0: 988
0.12.0: 1008
1.0.0: 1040
1.0.1: 1040
1.0.2: 1040
1.1.1: 1092
1.1.2: 1096
```

```ruby
versions = %w|0.6.0 0.7.0 0.8.0 0.9.0 0.10.0 0.11.0 0.12.0 1.0.0 1.0.1 1.0.2 1.1.1 1.1.2|

system("rm -rf .git sizes")
system("git init")

versions.each do |version|
  puts "** Downloading #{version}"
  system("curl -O http://duktape.org/duktape-#{version}.tar.xz")
  puts "** Unpacking"
  system("tar xf duktape-#{version}.tar.xz")
  system("cp duktape-#{version}/src/* .")
  system("git add duktape.{c,h}")
  system("git commit -m'#{version}'")
  system("git gc --aggressive")
  size = `du -sk .git`.to_i
  system("echo #{version}: #{size} >> sizes")
end
```

**Comment by svaarala** [comment]
Hi guys, not sure if this is relevant, but Duktape releases are also available here in both tar.xz and unpacked form (each tag in the repo is the unpacked release):

- https://github.com/svaarala/duktape-releases

**Comment by josh** [comment]
gziping packfiles works pretty well.

@judofyr is that enough evidence to just track in git or would you still prefer it be external?
